/**
 * examPages.ts
 * Data for Indian government exam photo & signature requirements.
 * Each entry generates one page at /exam-photo-size/[slug]
 * and appears as a row on the hub page /indian-exam-photo-size.
 *
 * ADD MORE EXAMS — just push a new object into examRequirements below.
 * The hub listing and per-exam tool pages update automatically.
 */

export interface ExamPhotoRequirement {
  /** Exam name shown in headings */
  name: string;
  /** Conducting body, e.g. "NTA", "UPSC", "SSC" */
  body: string;
  /** One-line exam category */
  category: string;
  /** Photo pixel width required by the portal */
  photoW: number;
  /** Photo pixel height required by the portal */
  photoH: number;
  /** Maximum photo file size in KB */
  photoMaxKb: number;
  /** Minimum photo file size in KB (some portals reject files that are too small) */
  photoMinKb?: number;
  /** Signature pixel width */
  signW: number;
  /** Signature pixel height */
  signH: number;
  /** Maximum signature file size in KB */
  signMaxKb: number;
  /** Minimum signature file size in KB (some portals reject files that are too small) */
  signMinKb?: number;
  /** Accepted output format */
  format: "jpeg" | "png" | "jpeg_or_png";
  /** Background requirement note */
  background: string;
  /** Extra warnings / notes shown on the page */
  notes: string[];
  /** Official source URL */
  sourceUrl?: string;
  /** Display label for the source URL */
  sourceLabel?: string;
}

export interface ExamPage {
  slug: string;
  exam: ExamPhotoRequirement;
  title: string;
  h1: string;
  description: string;
  intro: string;
}

// ─── Raw exam data ────────────────────────────────────────────────────────────

export const examRequirements: ExamPhotoRequirement[] = [
  {
    name: "NEET UG",
    body: "NTA",
    category: "Medical Entrance",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 30,
    format: "jpeg",
    background: "White or off-white background, both ears visible",
    notes: [
      "Photo must be taken recently — not more than 3 months old.",
      "Candidate name and date of photograph must be printed at the bottom of the photo.",
      "Signature must be on plain white paper with a black or blue pen.",
      "Requirements can change each cycle — always verify from the official NTA NEET notice.",
    ],
    sourceUrl: "https://neet.nta.nic.in",
    sourceLabel: "neet.nta.nic.in",
  },
  {
    name: "UPSC CSE",
    body: "UPSC",
    category: "Civil Services",
    photoW: 600,
    photoH: 800,
    photoMaxKb: 300,
    photoMinKb: 10,
    signW: 800,
    signH: 200,
    signMaxKb: 300,
    format: "jpeg",
    background: "Light or white background, face clearly visible",
    notes: [
      "Photo should be clear with the face covering a large portion of the frame.",
      "Signature should be on plain white paper, signed with black or blue ink pen.",
      "Confirm exact KB limits from the current UPSC notification before submitting.",
    ],
    sourceUrl: "https://upsconline.nic.in",
    sourceLabel: "upsconline.nic.in",
  },
  {
    name: "SSC CGL / CHSL",
    body: "SSC",
    category: "Staff Selection Commission",
    photoW: 413,
    photoH: 531,
    photoMaxKb: 100,
    photoMinKb: 20,
    signW: 800,
    signH: 200,
    signMaxKb: 100,
    format: "jpeg",
    background: "White background, no cap, no sunglasses",
    notes: [
      "Both eyes must be clearly visible and the face must be unobstructed.",
      "Photo must be recent — not older than 3 months from the date of application.",
      "Signature must be in running hand (cursive) — not in block/capital letters.",
      "Dimension requirements vary slightly per SSC cycle — always check the official notice.",
    ],
    sourceUrl: "https://ssc.nic.in",
    sourceLabel: "ssc.nic.in",
  },
  {
    name: "JEE Main",
    body: "NTA",
    category: "Engineering Entrance",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 300,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 300,
    format: "jpeg",
    background: "White or light coloured background, no dark backgrounds",
    notes: [
      "Candidate's name and date of photography must be printed at the bottom of the photograph.",
      "Photo taken with webcam from a mobile or laptop is NOT accepted.",
      "Face should cover at least 50% of the photo area — no excessive headroom.",
      "Always verify from the active NTA JEE Main Information Bulletin for the current session.",
    ],
    sourceUrl: "https://jeemain.nta.nic.in",
    sourceLabel: "jeemain.nta.nic.in",
  },
  {
    name: "IBPS PO / Clerk",
    body: "IBPS",
    category: "Banking",
    photoW: 390,
    photoH: 500,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 800,
    signH: 200,
    signMaxKb: 50,
    format: "jpeg",
    background: "White or light background, no cap, no sunglasses",
    notes: [
      "Minimum 390×500 px; portal typically accepts up to 590×800 px for photos.",
      "Signature file must be between 10 KB and 50 KB.",
      "Both photo and signature should be scanned on plain white paper.",
      "Requirements may differ between PO, Clerk, SO, and RRB sub-notifications — verify each time.",
    ],
    sourceUrl: "https://www.ibps.in",
    sourceLabel: "ibps.in",
  },
  {
    name: "RRB NTPC / Group D",
    body: "Railway Recruitment Boards",
    category: "Railways",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 300,
    photoMinKb: 20,
    signW: 800,
    signH: 200,
    signMaxKb: 300,
    format: "jpeg",
    background: "White or light background, no spectacles",
    notes: [
      "Exact KB limits can vary by RRB zone — always check your specific board's notification.",
      "Photo must not be older than 3 months from the date of application.",
      "Spectacles are not allowed in the photo for most RRB notifications.",
    ],
    sourceUrl: "https://indianrailways.gov.in",
    sourceLabel: "indianrailways.gov.in",
  },
  {
    name: "GATE",
    body: "IITs / IISc",
    category: "PG Engineering Entrance",
    photoW: 480,
    photoH: 640,
    photoMaxKb: 500,
    photoMinKb: 5,
    signW: 800,
    signH: 200,
    signMaxKb: 500,
    format: "jpeg",
    background: "Light or white background, face clearly visible",
    notes: [
      "GATE is conducted by IITs and IISc on rotation — the organising institute changes annually.",
      "Photo must clearly show the candidate's face with name and date printed below.",
      "The organising institute may update limits — always refer to the current GATE official website.",
    ],
    sourceUrl: "https://gate.iitkgp.ac.in",
    sourceLabel: "gate.iitkgp.ac.in",
  },
  {
    name: "CAT",
    body: "IIM",
    category: "MBA Entrance",
    photoW: 430,
    photoH: 596,
    photoMaxKb: 80,
    photoMinKb: 20,
    signW: 720,
    signH: 240,
    signMaxKb: 80,
    format: "jpeg",
    background: "White or light background, no sunglasses, no cap",
    notes: [
      "Both photo and signature must be in colour.",
      "Blurred or unclear photos will cause rejection at the time of document verification.",
      "Confirm limits from the CAT admission notice issued by the current year's convener IIM.",
    ],
    sourceUrl: "https://iimcat.ac.in",
    sourceLabel: "iimcat.ac.in",
  },
  {
    name: "CUET UG",
    body: "NTA",
    category: "Central University Entrance",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 300,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 300,
    format: "jpeg",
    background: "White or light background, name and date printed below",
    notes: [
      "Candidate's name and date of photograph must be printed on the photo.",
      "Requirements are largely similar to other NTA exams but verify annually from the official CUET bulletin.",
    ],
    sourceUrl: "https://cuet.samarth.ac.in",
    sourceLabel: "cuet.samarth.ac.in",
  },
  {
    name: "PAN Card Application",
    body: "NSDL / Protean",
    category: "Government Document",
    photoW: 213,
    photoH: 213,
    photoMaxKb: 50,
    signW: 400,
    signH: 160,
    signMaxKb: 30,
    format: "jpeg",
    background: "White background, both ears visible, no sunglasses",
    notes: [
      "Photo must be at least 200×200 px for the NSDL portal.",
      "Both ears must be visible and the face should clearly appear in the photo.",
      "Signature should be signed in black ink on plain white paper.",
      "Confirm exact requirements from the NSDL/Protean PAN portal before applying.",
    ],
    sourceUrl: "https://www.onlineservices.nsdl.com",
    sourceLabel: "onlineservices.nsdl.com",
  },
  {
    name: "JEE Advanced",
    body: "IITs (Rotating)",
    category: "Engineering Entrance",
    photoW: 480,
    photoH: 640,
    photoMaxKb: 300,
    photoMinKb: 10,
    signW: 800,
    signH: 200,
    signMaxKb: 30,
    signMinKb: 5,
    format: "jpeg",
    background: "White or very light background, full face visible",
    notes: [
      "Only qualified JEE Main candidates are eligible to upload files here.",
      "Photo must be recent, preferably matching or highly similar to the JEE Main upload.",
      "Signature must be on a white sheet with a black ink pen only.",
    ],
    sourceUrl: "https://jeeadv.ac.in",
    sourceLabel: "jeeadv.ac.in",
  },
  {
    name: "CLAT",
    body: "Consortium of NLUs",
    category: "Law Entrance",
    photoW: 400,
    photoH: 500,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 100,
    signMinKb: 10,
    format: "jpeg",
    background: "Light background, plain and front-facing view",
    notes: [
      "Both photo and signature must be exceptionally clear; grainy or blurred images will face immediate rejection.",
      "Requires a separate document upload for Category Certificate if applicable (Max 2MB, PDF format).",
    ],
    sourceUrl: "https://consortiumofnlus.ac.in",
    sourceLabel: "consortiumofnlus.ac.in",
  },
  {
    name: "NDA / CDS",
    body: "UPSC",
    category: "Defense Entrance",
    photoW: 350,
    photoH: 350,
    photoMaxKb: 300,
    photoMinKb: 20,
    signW: 350,
    signH: 350,
    signMaxKb: 300,
    signMinKb: 20,
    format: "jpeg",
    background: "Plain white or light gray background",
    notes: [
      "UPSC strictly enforces uniform dimensions (square ratio 350x350 to 1000x1000 pixels accepted).",
      "Requires an identity card document (Aadhaar, Voter ID, etc.) uploaded within 20 KB to 300 KB limits.",
    ],
    sourceUrl: "https://upsconline.nic.in",
    sourceLabel: "upsconline.nic.in",
  },
  {
    name: "SBI PO",
    body: "State Bank of India",
    category: "Banking",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 140,
    signH: 60,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "White background, preferred with a relaxed, neutral face",
    notes: [
      "Signature in CAPITAL LETTERS is strictly rejected.",
      "Requires Left Thumb Impression (20 KB - 50 KB) and a Handwritten Declaration text file (50 KB - 100 KB).",
    ],
    sourceUrl: "https://bank.sbi/careers",
    sourceLabel: "bank.sbi",
  },
  {
    name: "UGC NET",
    body: "NTA",
    category: "Eligibility Test",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 30,
    signMinKb: 4,
    format: "jpeg",
    background: "White background, 80% face coverage visible without mask",
    notes: [
      "Spectacles are allowed only if regularly worn; tinted glasses/sunglasses are strictly banned.",
      "Keep 6 to 8 identical physical prints handy for exam center verification.",
    ],
    sourceUrl: "https://ugcnet.nta.nic.in",
    sourceLabel: "ugcnet.nta.nic.in",
  },
  {
    name: "NEET PG",
    body: "NBEMS",
    category: "Medical Post-Graduate",
    photoW: 600,
    photoH: 600,
    photoMaxKb: 80,
    photoMinKb: 10,
    signW: 600,
    signH: 300,
    signMaxKb: 80,
    signMinKb: 10,
    format: "jpeg",
    background: "Strictly solid white background",
    notes: [
      "Requires a real-time photograph taken via webcam during registration alongside an uploaded passphoto.",
      "Thumb impression must be uploaded cleanly on white paper with blue/black ink (10 KB - 80 KB).",
    ],
    sourceUrl: "https://natboard.edu.in",
    sourceLabel: "natboard.edu.in",
  },
  {
    name: "XAT",
    body: "XLRI Jamshedpur",
    category: "Management Entrance",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 140,
    signH: 60,
    signMaxKb: 50,
    signMinKb: 20,
    format: "jpeg",
    background: "Light background, preferably white",
    notes: [
      "Photo must not be older than 6 months.",
      "Ensure the signature matches across all subsequent admissions and physical check-ins at XLRI or affiliated nodes.",
    ],
    sourceUrl: "https://xatonline.in",
    sourceLabel: "xatonline.in",
  },
  {
    name: "BITSAT",
    body: "BITS Pilani",
    category: "Engineering Entrance",
    photoW: 400,
    photoH: 500,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 50,
    signMinKb: 10,
    format: "jpeg",
    background: "White or off-white background",
    notes: [
      "Both background color and lightning must be uniform across the photograph.",
      "Selfies or casually cropped mobile photos will lead to instant application disqualification.",
    ],
    sourceUrl: "https://bitsadmission.com",
    sourceLabel: "bitsadmission.com",
  },
  {
    name: "AFCAT",
    body: "Indian Air Force",
    category: "Defense Entrance",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 50,
    photoMinKb: 10,
    signW: 140,
    signH: 60,
    signMaxKb: 50,
    signMinKb: 10,
    format: "jpeg",
    background: "Light-colored background, preferably plain white",
    notes: [
      "Requires candidate's left thumb impression image (10 KB to 50 KB).",
      "The passport photograph must strictly capture the natural skin tone without cosmetic digital filters.",
    ],
    sourceUrl: "https://afcat.cdac.in",
    sourceLabel: "afcat.cdac.in",
  },
  {
    name: "MHT CET",
    body: "State CET Cell Maharashtra",
    category: "State Engineering/Pharma",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 50,
    photoMinKb: 15,
    signW: 400,
    signH: 150,
    signMaxKb: 30,
    signMinKb: 5,
    format: "jpeg",
    background: "Light or white background",
    notes: [
      "Signature must be done on white paper using a black ink pen exclusively.",
      "Identity proof documents like Aadhaar card or PAN card must be scanned and uploaded in clear view.",
    ],
    sourceUrl: "https://cetcell.mahacet.org",
    sourceLabel: "mahacet.org",
  },
  {
    name: "NIFT",
    body: "National Institute of Fashion Technology",
    category: "Design Entrance",
    photoW: 413,
    photoH: 531,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 800,
    signH: 200,
    signMaxKb: 50,
    signMinKb: 5,
    format: "jpeg",
    background: "Light uniform background, no gradients or shadows",
    notes: [
      "Image should display a clear frontal facial configuration.",
      "Ensure the exact file properties do not contain metadata that violates parsing restrictions on the NIFT admissions server.",
    ],
    sourceUrl: "https://nift.ac.in",
    sourceLabel: "nift.ac.in",
  },
  {
    name: "VITEEE",
    body: "VIT University",
    category: "Engineering Entrance",
    photoW: 350,
    photoH: 450,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 200,
    signMinKb: 10,
    format: "jpeg",
    background: "White or very light solid color background",
    notes: [
      "Photographs with red eyes or camera-flash glares on spectacles will be rejected.",
      "The portal automatically resizes file displays, but maintaining the proper aspect ratio safeguards image clarity.",
    ],
    sourceUrl: "https://viteee.vit.ac.in",
    sourceLabel: "viteee.vit.ac.in",
  },
  {
    name: "NIMCET",
    body: "NITs (Rotating)",
    category: "MCA Entrance",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 150,
    photoMinKb: 50,
    signW: 400,
    signH: 150,
    signMaxKb: 50,
    signMinKb: 10,
    format: "jpeg",
    background: "Plain white background only",
    notes: [
      "The photo uploaded should distinctly showcase both ears facing horizontally parallel to the frame.",
      "Check current coordinating NIT instructions as strictness around background tints changes annually.",
    ],
    sourceUrl: "https://nimcet.in",
    sourceLabel: "nimcet.in",
  },
  {
    name: "RBI Grade B",
    body: "Reserve Bank of India",
    category: "Banking / Regulatory",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 140,
    signH: 60,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "White background, neutral facial posture",
    notes: [
      "Capital letter signatures are invalid.",
      "Thumb impression (left hand, white paper, blue/black ink) and a handwritten declaration copy must accompany the application files.",
    ],
    sourceUrl: "https://www.rbi.org.in",
    sourceLabel: "rbi.org.in",
  },
  {
    name: "CTET",
    body: "CBSE",
    category: "Teacher Eligibility",
    photoW: 350,
    photoH: 450,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 350,
    signH: 150,
    signMaxKb: 30,
    signMinKb: 3,
    format: "jpeg",
    background:
      "White or clear light background, full face view directly facing the camera",
    notes: [
      "Photo dimensions must mathematically map closely to 3.5 cm (width) x 4.5 cm (height).",
      "The signature must be 3.5 cm (length) x 1.5 cm (height) and done with a black/blue pen.",
      "Photos will be matched with the physical candidate at the exam center — avoid digital retouching.",
    ],
    sourceUrl: "https://ctet.nic.in",
    sourceLabel: "ctet.nic.in",
  },
  {
    name: "CSIR NET",
    body: "NTA",
    category: "Eligibility Test",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 30,
    signMinKb: 4,
    format: "jpeg",
    background:
      "White background, 80% face visible (without mask) including ears",
    notes: [
      "Matches standard NTA parameters; ensure no sunglasses or tinted spectacles are worn.",
      "A physical copy of the exact same uploaded photograph must be brought to the exam center to paste on the attendance sheet.",
    ],
    sourceUrl: "https://csirnet.nta.nic.in",
    sourceLabel: "csirnet.nta.nic.in",
  },
  {
    name: "CMAT",
    body: "NTA",
    category: "Management Entrance",
    photoW: 800,
    photoH: 1000,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 800,
    signH: 300,
    signMaxKb: 30,
    signMinKb: 4,
    format: "jpeg",
    background: "White background, clear contrast",
    notes: [
      "Follows identical parameters to other NTA exams (JEE/NEET).",
      "Candidates wearing traditional/religious dress must report early to the exam center for thorough frisking.",
    ],
    sourceUrl: "https://cmat.nta.nic.in",
    sourceLabel: "cmat.nta.nic.in",
  },
  {
    name: "SNAP",
    body: "Symbiosis International",
    category: "Management Entrance",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 140,
    signH: 60,
    signMaxKb: 50,
    signMinKb: 10,
    format: "jpeg",
    background: "White or very light color background",
    notes: [
      "Photo should not be more than three months old.",
      "Scanned signature must be against a clear white background and visibly readable without zooming.",
    ],
    sourceUrl: "https://www.snaptest.org",
    sourceLabel: "snaptest.org",
  },
  {
    name: "MAT",
    body: "AIMA",
    category: "Management Entrance",
    photoW: 250,
    photoH: 250,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 250,
    signH: 150,
    signMaxKb: 40,
    signMinKb: 5,
    format: "jpeg",
    background: "Light uniform background",
    notes: [
      "Avoid harsh flash shadows; face should be fully illuminated.",
      "Signature should be in black ink and strictly contained within a cropped bounding box before uploading.",
    ],
    sourceUrl: "https://mat.aima.in",
    sourceLabel: "mat.aima.in",
  },
  {
    name: "LIC AAO / ADO",
    body: "LIC of India",
    category: "Insurance",
    photoW: 200,
    photoH: 230,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 140,
    signH: 60,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "White background",
    notes: [
      "Follows standard IBPS portal banking protocols.",
      "Signature must not be in capital letters. A handwritten declaration (50 KB – 100 KB) and left thumb impression are also required.",
    ],
    sourceUrl: "https://licindia.in",
    sourceLabel: "licindia.in",
  },
  {
    name: "SSC GD Constable",
    body: "SSC",
    category: "Paramilitary / Police",
    photoW: 200,
    photoH: 240,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 240,
    signH: 80,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "Plain white background",
    notes: [
      "Spectacles and caps are strictly prohibited. Applications will be summarily rejected if the photo has glasses.",
      "The SSC portal has been recently updated to mandate live-camera capture alongside or in place of scanned uploads.",
    ],
    sourceUrl: "https://ssc.gov.in",
    sourceLabel: "ssc.gov.in",
  },
  {
    name: "RRB ALP",
    body: "Railway Recruitment Boards",
    category: "Railways",
    photoW: 320,
    photoH: 240,
    photoMaxKb: 70,
    photoMinKb: 30,
    signW: 140,
    signH: 60,
    signMaxKb: 70,
    signMinKb: 30,
    format: "jpeg",
    background: "White background, face taking up 80% of the frame",
    notes: [
      "Unlike some exams, RRB specifies very specific mid-tier kb limits (30-70kb) across both photo and sign.",
      "Multiple identical photos must be printed and retained for subsequent document verification stages.",
    ],
    sourceUrl: "https://indianrailways.gov.in",
    sourceLabel: "indianrailways.gov.in",
  },
  {
    name: "WBJEE",
    body: "WBJEEB",
    category: "State Engineering",
    photoW: 200,
    photoH: 250,
    photoMaxKb: 200,
    photoMinKb: 10,
    signW: 150,
    signH: 50,
    signMaxKb: 30,
    signMinKb: 4,
    format: "jpeg",
    background: "Light background, face looking directly into the camera",
    notes: [
      "High-quality scanning required; mobile phone photographs of passport photos are frequently rejected.",
      "If any defect is detected, the board sends an SMS/Email to correct it within a very short 1-2 day window.",
    ],
    sourceUrl: "https://wbjeeb.nic.in",
    sourceLabel: "wbjeeb.nic.in",
  },
  {
    name: "TS EAMCET / EAPCET",
    body: "JNTUH",
    category: "State Engineering/Pharma",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 50,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 30,
    signMinKb: 10,
    format: "jpeg",
    background: "White or very light background",
    notes: [
      "Candidates applying via TS online centers typically have their photos cropped by the operators, but self-applicants must adhere strictly to the 50kb limit.",
      "Signature must be done on white paper with a black pen.",
    ],
    sourceUrl: "https://eapcet.tsche.ac.in",
    sourceLabel: "eapcet.tsche.ac.in",
  },
  {
    name: "AP EAPCET",
    body: "JNTUA",
    category: "State Engineering/Pharma",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 50,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 30,
    signMinKb: 10,
    format: "jpeg",
    background: "White or light background",
    notes: [
      "Follows exact identical portal guidelines to TS EAMCET.",
      "Ensure the aspect ratio isn't skewed when compressing to meet the <50kb requirement.",
    ],
    sourceUrl: "https://cets.apsche.ap.gov.in",
    sourceLabel: "cets.apsche.ap.gov.in",
  },
  {
    name: "COMEDK UGET",
    body: "Consortium of Medical, Engineering and Dental Colleges of Karnataka",
    category: "Engineering Entrance",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 80,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 80,
    signMinKb: 10,
    format: "jpeg",
    background: "White or off-white background",
    notes: [
      "Requires candidate's photo, signature, AND parent/guardian signature (also max 80 KB).",
      "The candidate must be looking straight ahead with a neutral expression.",
    ],
    sourceUrl: "https://www.comedk.org",
    sourceLabel: "comedk.org",
  },
  {
    name: "KEAM",
    body: "CEE Kerala",
    category: "State Engineering/Pharma",
    photoW: 150,
    photoH: 200,
    photoMaxKb: 100,
    photoMinKb: 15,
    signW: 150,
    signH: 100,
    signMaxKb: 30,
    signMinKb: 10,
    format: "jpeg",
    background: "White or very light background",
    notes: [
      "Name of the candidate and the date of taking the photograph MUST be printed at the bottom of the photo.",
      "Dimensions strictly mandate exactly 150 pixels width for both photo and signature.",
    ],
    sourceUrl: "https://cee.kerala.gov.in",
    sourceLabel: "cee.kerala.gov.in",
  },
  {
    name: "KCET",
    body: "KEA",
    category: "State Engineering/Pharma",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 40,
    photoMinKb: 5,
    signW: 400,
    signH: 150,
    signMaxKb: 40,
    signMinKb: 5,
    format: "jpeg",
    background: "Light background",
    notes: [
      "Files must strictly be below 40 KB, making compression efficiency very important.",
      "Left Hand Thumb Impression is also required within the same 5-40 KB limits.",
    ],
    sourceUrl: "https://cetonline.karnataka.gov.in/kea",
    sourceLabel: "cetonline.karnataka.gov.in/kea",
  },
  {
    name: "TANCET",
    body: "Anna University",
    category: "State Post-Graduate Entrance",
    photoW: 240,
    photoH: 320,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 250,
    signH: 70,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "White or light uniform background",
    notes: [
      "Photo dimensions should align with a 240 x 320 px aspect ratio to avoid stretching on the hall ticket.",
      "Ensure clarity of the face; heavily pixelated uploads will not be permitted at the testing center.",
    ],
    sourceUrl: "https://tancet.annauniv.edu",
    sourceLabel: "tancet.annauniv.edu",
  },
  {
    name: "NID DAT",
    body: "National Institute of Design",
    category: "Design Entrance",
    photoW: 413,
    photoH: 531,
    photoMaxKb: 200,
    photoMinKb: 50,
    signW: 800,
    signH: 200,
    signMaxKb: 200,
    signMinKb: 50,
    format: "jpeg",
    background: "White background only",
    notes: [
      "Strict minimum 50 KB requirement prevents candidates from uploading overly-compressed, low-quality images.",
      "As a design institute, NID rejects severely skewed or stretched aspect ratios.",
    ],
    sourceUrl: "https://admissions.nid.edu",
    sourceLabel: "admissions.nid.edu",
  },
  {
    name: "UCEED / CEED",
    body: "IIT Bombay",
    category: "Design Entrance",
    photoW: 400,
    photoH: 500,
    photoMaxKb: 300,
    photoMinKb: 50,
    signW: 800,
    signH: 200,
    signMaxKb: 300,
    signMinKb: 10,
    format: "jpeg",
    background: "White or very light background",
    notes: [
      "Recent color photograph with full face clearly visible. No caps or dark glasses.",
      "Requires a cropped image without any borders or borders containing personal text/watermarks.",
    ],
    sourceUrl: "https://www.uceed.iitb.ac.in",
    sourceLabel: "uceed.iitb.ac.in",
  },
  {
    name: "NATA",
    body: "Council of Architecture",
    category: "Architecture Entrance",
    photoW: 300,
    photoH: 400,
    photoMaxKb: 100,
    photoMinKb: 10,
    signW: 400,
    signH: 150,
    signMaxKb: 30,
    signMinKb: 4,
    format: "jpeg",
    background: "Light background",
    notes: [
      "Standard high-contrast color photo. Do not scan existing printed photos; use a digital source.",
      "Signature must correspond precisely to the one used during center verification.",
    ],
    sourceUrl: "https://www.nata.in",
    sourceLabel: "nata.in",
  },
  {
    name: "UPPSC PCS",
    body: "Uttar Pradesh Public Service Commission",
    category: "State Civil Services",
    photoW: 180,
    photoH: 216,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 216,
    signH: 108,
    signMaxKb: 30,
    signMinKb: 10,
    format: "jpeg",
    background: "White or light background",
    notes: [
      'Historically, UPPSC often requires a "Combined Image" (photo pasted on top of signature in a single 3.5cm x 6cm template), but the OTR (One Time Registration) portal separates them to standard limits.',
      "Make sure both files are highly legible under 50KB limits.",
    ],
    sourceUrl: "https://uppsc.up.nic.in",
    sourceLabel: "uppsc.up.nic.in",
  },
  {
    name: "MPSC Rajyaseva",
    body: "Maharashtra Public Service Commission",
    category: "State Civil Services",
    photoW: 275,
    photoH: 354,
    photoMaxKb: 50,
    photoMinKb: 20,
    signW: 275,
    signH: 118,
    signMaxKb: 20,
    signMinKb: 10,
    format: "jpeg",
    background: "White background preferred",
    notes: [
      "Must be uploaded to the MPSC profile section before applying for the actual examination.",
      "Signature must be clear running hand — avoid disjointed or block capital letters.",
    ],
    sourceUrl: "https://mpsc.gov.in",
    sourceLabel: "mpsc.gov.in",
  },
];

// ─── Page builder ─────────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildExamPage(req: ExamPhotoRequirement): ExamPage {
  const fragment = slugify(req.name);
  const slug = `exam-photo-size/${fragment}`;
  const h1 = `${req.name} Photo & Signature Size`;
  const title = `${req.name} Photo Size — ${req.photoW}×${req.photoH} px, Max ${req.photoMaxKb} KB | Crop & Fix Free`;
  const description = `${req.name} (${req.body}) photo upload requirements: ${req.photoW}×${req.photoH} px, max ${req.photoMaxKb} KB, JPEG format. Crop and compress your photo directly in the browser — no upload, no account, 100% private.`;
  const intro = `The <strong>${req.name}</strong> (${req.body}) portal requires a photo of <strong>${req.photoW}×${req.photoH} px</strong> (max ${req.photoMaxKb} KB, JPEG) and a signature of <strong>${req.signW}×${req.signH} px</strong> (max ${req.signMaxKb} KB). Use the three steps below to crop, resize, and compress both — entirely in your browser, nothing is uploaded.`;

  return { slug, exam: req, title, h1, description, intro };
}

export const examPages: ExamPage[] = examRequirements.map(buildExamPage);

export function getExamPage(slugFragment: string): ExamPage | undefined {
  return examPages.find(
    (p) =>
      p.slug === `exam-photo-size/${slugFragment}` || p.slug === slugFragment,
  );
}

/** Returns the URL slug fragment used after /exam-photo-size/ */
export function examSlugFragment(page: ExamPage): string {
  return page.slug.replace("exam-photo-size/", "");
}
