import { categoryLabels, getPlatformPageFormats, imageSizeIntentPages, type PlatformCategory } from './platforms';

export type ImageSizeForCategory = PlatformCategory | 'popular' | 'marketplace' | 'website' | 'document' | 'apparel' | 'email' | 'education' | 'visa' | 'messaging' | 'misc';

export interface ImageSizeForOption {
  term: string;
  href: string;
  category: ImageSizeForCategory;
  categoryLabel: string;
  w?: number;
  h?: number;
  ratio?: string;
  description: string;
  aliases: string[];
  featured?: boolean;
}

const categoryLabelMap: Record<ImageSizeForCategory, string> = {
  ...categoryLabels,
  popular: 'Popular',
  marketplace: 'Marketplace',
  website: 'Website',
  document: 'Document',
  apparel: 'Apparel',
  email: 'Email',
  education: 'Education',
  visa: 'Visa / ID',
  messaging: 'Messaging',
  misc: 'Other',
};

function option(input: Omit<ImageSizeForOption, 'categoryLabel' | 'aliases'> & { aliases?: string[] }): ImageSizeForOption {
  return {
    ...input,
    categoryLabel: categoryLabelMap[input.category],
    aliases: input.aliases || [],
  };
}

const curatedOptions: ImageSizeForOption[] = [
  option({
    term: 'linkedin post',
    href: '/linkedin-post-image-size',
    category: 'popular',
    w: 1200,
    h: 628,
    ratio: '1.91:1',
    description: 'Landscape LinkedIn post preset, with square and vertical options on the page.',
    aliases: ['linkedin post image', 'linkedin feed post', 'linkedin ad image'],
    featured: true,
  }),
  option({
    term: 'linkedin cover',
    href: '/linkedin-cover-image-size',
    category: 'popular',
    w: 1584,
    h: 396,
    ratio: '4:1',
    description: 'Profile background first, plus LinkedIn Page cover guidance.',
    aliases: ['linkedin header', 'linkedin banner', 'linkedin background photo'],
    featured: true,
  }),
  option({
    term: 'google forms header',
    href: '/google-forms-header-image-size',
    category: 'popular',
    w: 1600,
    h: 400,
    ratio: '4:1',
    description: 'Practical header template for Google Forms theme images.',
    aliases: ['google form header', 'forms banner', 'google forms banner'],
    featured: true,
  }),
  option({
    term: 'twitter image',
    href: '/twitter-image-size',
    category: 'popular',
    w: 1200,
    h: 675,
    ratio: '16:9',
    description: 'Twitter/X post image, with header and profile presets nearby.',
    aliases: ['x image', 'twitter x image', 'twitter post'],
    featured: true,
  }),
  option({
    term: 'whatsapp dp',
    href: '/whatsapp-profile-photo-size',
    category: 'social',
    w: 500,
    h: 500,
    ratio: '1:1',
    description: 'Square profile photo preset for WhatsApp display pictures.',
    aliases: ['whatsapp profile photo', 'whatsapp display picture'],
    featured: true,
  }),
  option({
    term: 'youtube shorts',
    href: '/youtube-shorts-size',
    category: 'video',
    w: 1080,
    h: 1920,
    ratio: '9:16',
    description: 'Vertical video frame for Shorts, Reels, TikTok, and stories.',
    aliases: ['youtube short', 'shorts thumbnail', 'shorts video'],
    featured: true,
  }),
  option({
    term: 'pan card',
    href: '/crop-and-resize?tw=213&th=213',
    category: 'document',
    w: 213,
    h: 213,
    ratio: '1:1',
    description: 'Document-photo workspace for PAN card uploads. Check the destination form for exact KB and pixel rules.',
    aliases: ['pan card photo', 'pan photo', 'pan card upload'],
    featured: true,
  }),
  option({
    term: 'dsssb',
    href: '/crop-and-resize?tw=213&th=213',
    category: 'document',
    w: 213,
    h: 213,
    ratio: '1:1',
    description: 'Document-photo workspace for DSSSB forms. Confirm the current form instructions before final upload.',
    aliases: ['dsssb photo', 'dsssb signature', 'dsssb upload'],
  }),
  option({
    term: 'wallpaper',
    href: '/screen-iphone-16-pro-size',
    category: 'video',
    w: 1206,
    h: 2622,
    ratio: '19.5:9',
    description: 'Phone wallpaper starting point, with screen presets available in the full list.',
    aliases: ['iphone wallpaper', 'phone wallpaper', 'mobile wallpaper'],
    featured: true,
  }),
  option({
    term: 'instagram dp',
    href: '/instagram-profile-photo-size',
    category: 'social',
    w: 320,
    h: 320,
    ratio: '1:1',
    description: 'Square profile photo preset for Instagram display pictures.',
    aliases: ['instagram profile picture', 'instagram profile photo'],
    featured: true,
  }),
  option({
    term: 'instagram post',
    href: '/instagram-square-post-size',
    category: 'social',
    w: 1080,
    h: 1080,
    ratio: '1:1',
    description: 'Start with square posts, then switch to portrait or landscape Instagram presets.',
    aliases: ['instagram feed post', 'ig post', 'instagram square post'],
    featured: true,
  }),
  option({
    term: 'printing',
    href: '/print-a4-portrait-size',
    category: 'print',
    w: 2480,
    h: 3508,
    ratio: 'sqrt2:1',
    description: 'A4 print preset at 300 DPI, with more paper sizes in the print section.',
    aliases: ['print image', 'printing photo', 'photo printing'],
    featured: true,
  }),
  option({
    term: 'amazon listing',
    href: '/crop-and-resize?tw=2000&th=2000',
    category: 'marketplace',
    w: 2000,
    h: 2000,
    ratio: '1:1',
    description: 'Practical square product-image workspace for marketplace listings.',
    aliases: ['amazon product listing', 'amazon product image', 'amazon listing photo'],
  }),
  option({
    term: 'amazon product listing',
    href: '/crop-and-resize?tw=2000&th=2000',
    category: 'marketplace',
    w: 2000,
    h: 2000,
    ratio: '1:1',
    description: 'Square product image workspace for Amazon catalog uploads.',
    aliases: ['amazon listing', 'amazon product image'],
  }),
  option({
    term: 'flipkart listing',
    href: '/crop-and-resize?tw=2000&th=2000',
    category: 'marketplace',
    w: 2000,
    h: 2000,
    ratio: '1:1',
    description: 'Square product image workspace for Flipkart-style marketplace uploads.',
    aliases: ['flipkart product listing', 'flipkart product image'],
  }),
  option({
    term: 'a4 paper',
    href: '/print-a4-portrait-size',
    category: 'print',
    w: 2480,
    h: 3508,
    ratio: 'sqrt2:1',
    description: 'A4 portrait at 300 DPI, useful for print-ready documents.',
    aliases: ['a4 size', 'a4 paper size', 'a4 print'],
  }),
  option({
    term: 'a logo',
    href: '/crop-and-resize?tw=512&th=512',
    category: 'website',
    w: 512,
    h: 512,
    ratio: '1:1',
    description: 'Square logo workspace for app icons, favicons, and profile marks.',
    aliases: ['logo', 'brand logo', 'website logo'],
  }),
  option({
    term: 'album',
    href: '/crop-and-resize?tw=3000&th=3000',
    category: 'popular',
    w: 3000,
    h: 3000,
    ratio: '1:1',
    description: 'Large square canvas for album art and cover uploads.',
    aliases: ['album cover', 'music cover', 'cover art'],
  }),
  option({
    term: 'album cover',
    href: '/crop-and-resize?tw=3000&th=3000',
    category: 'popular',
    w: 3000,
    h: 3000,
    ratio: '1:1',
    description: 'Large square cover-art workspace.',
    aliases: ['album', 'music cover', 'cover art'],
  }),
  option({
    term: 'adobe stock',
    href: '/crop-and-resize?tw=4000&th=3000',
    category: 'marketplace',
    w: 4000,
    h: 3000,
    ratio: '4:3',
    description: 'High-resolution stock-photo workspace. Confirm marketplace requirements before upload.',
    aliases: ['stock photo', 'adobe stock image', 'stock image'],
  }),
  option({
    term: 'blog post',
    href: '/crop-and-resize?tw=1200&th=630',
    category: 'website',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'Common blog and Open Graph preview image size.',
    aliases: ['blog', 'featured image', 'blog featured image'],
  }),
  option({
    term: 'blog',
    href: '/crop-and-resize?tw=1200&th=630',
    category: 'website',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'Common blog and social preview image size.',
    aliases: ['blog post', 'blog image', 'featured image'],
  }),
  option({
    term: 'website',
    href: '/crop-and-resize?tw=1200&th=630',
    category: 'website',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'General web sharing image workspace for page previews and cards.',
    aliases: ['website image', 'open graph image', 'og image'],
    featured: true,
  }),
  option({
    term: 'banner',
    href: '/crop-and-resize?tw=1920&th=640',
    category: 'website',
    w: 1920,
    h: 640,
    ratio: '3:1',
    description: 'Wide banner workspace for websites, headers, and campaigns.',
    aliases: ['website banner', 'header banner', 'hero banner'],
  }),
  option({
    term: 'banner printing',
    href: '/crop-and-resize?tw=3000&th=1000',
    category: 'print',
    w: 3000,
    h: 1000,
    ratio: '3:1',
    description: 'Wide print banner workspace. Set final pixels from your printer DPI and physical size.',
    aliases: ['print banner', 'large banner', 'printing banner'],
  }),
  option({
    term: 'behance portfolio',
    href: '/crop-and-resize?tw=1400&th=1050',
    category: 'website',
    w: 1400,
    h: 1050,
    ratio: '4:3',
    description: 'Portfolio project image workspace for Behance-style presentations.',
    aliases: ['behance project', 'behance', 'portfolio image'],
  }),
  option({
    term: 'behance project',
    href: '/crop-and-resize?tw=1400&th=1050',
    category: 'website',
    w: 1400,
    h: 1050,
    ratio: '4:3',
    description: 'Presentation image workspace for Behance projects.',
    aliases: ['behance portfolio', 'behance'],
  }),
  option({
    term: 'behance',
    href: '/crop-and-resize?tw=1400&th=1050',
    category: 'website',
    w: 1400,
    h: 1050,
    ratio: '4:3',
    description: 'Portfolio image workspace for Behance uploads.',
    aliases: ['behance project', 'behance portfolio'],
  }),
  option({
    term: 'bluesky',
    href: '/crop-and-resize?tw=1200&th=675',
    category: 'social',
    w: 1200,
    h: 675,
    ratio: '16:9',
    description: 'Social post image workspace for Bluesky and similar feeds.',
    aliases: ['bluesky post', 'bluesky image'],
  }),
  option({
    term: 'facebook ads',
    href: '/facebook-ad-single-image-size',
    category: 'social',
    w: 1200,
    h: 628,
    ratio: '1.91:1',
    description: 'Facebook single-image ad preset.',
    aliases: ['facebook ad', 'fb ads', 'meta ad image'],
  }),
  option({
    term: 'facebook post',
    href: '/facebook-post-image-size',
    category: 'social',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'Facebook feed post image preset.',
    aliases: ['fb post', 'facebook image post'],
  }),
  option({
    term: 'fb post',
    href: '/facebook-post-image-size',
    category: 'social',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'Facebook feed post image preset.',
    aliases: ['facebook post', 'facebook feed image'],
  }),
  option({
    term: 'facebook and instagram post',
    href: '/crop-and-resize?tw=1080&th=1080',
    category: 'social',
    w: 1080,
    h: 1080,
    ratio: '1:1',
    description: 'Square cross-posting workspace for Facebook and Instagram feeds.',
    aliases: ['meta post', 'facebook instagram post', 'fb instagram post'],
  }),
  option({
    term: 'facebook profile picture',
    href: '/facebook-profile-photo-size',
    category: 'social',
    w: 170,
    h: 170,
    ratio: '1:1',
    description: 'Facebook profile photo preset.',
    aliases: ['facebook dp', 'fb profile picture', 'facebook profile photo'],
  }),
  option({
    term: 'facebook',
    href: '/facebook-post-image-size',
    category: 'social',
    w: 1200,
    h: 630,
    ratio: '1.91:1',
    description: 'Start with a Facebook post image, then switch to cover, profile, story, or ad presets.',
    aliases: ['fb', 'facebook image'],
  }),
  option({
    term: 'facebook event',
    href: '/facebook-event-cover-size',
    category: 'social',
    w: 1920,
    h: 1005,
    ratio: '1.91:1',
    description: 'Facebook event cover image preset.',
    aliases: ['fb event', 'facebook event image'],
  }),
  option({
    term: 'facebook cover photo',
    href: '/facebook-cover-photo-size',
    category: 'social',
    w: 820,
    h: 312,
    ratio: '2.63:1',
    description: 'Facebook cover photo preset.',
    aliases: ['facebook cover', 'fb cover photo', 'facebook banner'],
  }),
  option({
    term: 'facebook event cover',
    href: '/facebook-event-cover-size',
    category: 'social',
    w: 1920,
    h: 1005,
    ratio: '1.91:1',
    description: 'Facebook event cover preset.',
    aliases: ['facebook event', 'fb event cover'],
  }),
  option({
    term: 'back of shirt',
    href: '/crop-and-resize?tw=4500&th=5400',
    category: 'apparel',
    w: 4500,
    h: 5400,
    ratio: '5:6',
    description: 'Large print artwork workspace for the back of a shirt.',
    aliases: ['shirt back print', 't shirt back design'],
  }),
  option({
    term: 'back of hoodie',
    href: '/crop-and-resize?tw=4500&th=5400',
    category: 'apparel',
    w: 4500,
    h: 5400,
    ratio: '5:6',
    description: 'Large apparel-artwork workspace for hoodie back prints.',
    aliases: ['hoodie back print', 'hoodie design'],
  }),
  option({
    term: 'adult medium shirt',
    href: '/crop-and-resize?tw=4500&th=5400',
    category: 'apparel',
    w: 4500,
    h: 5400,
    ratio: '5:6',
    description: 'Print artwork workspace for adult medium shirt designs.',
    aliases: ['medium shirt design', 'adult medium t shirt'],
  }),
  option({
    term: 'a large shirt',
    href: '/crop-and-resize?tw=4500&th=5400',
    category: 'apparel',
    w: 4500,
    h: 5400,
    ratio: '5:6',
    description: 'Print artwork workspace for large shirt designs.',
    aliases: ['large shirt design', 'large t shirt'],
  }),
  option({
    term: 'a 3t shirt',
    href: '/crop-and-resize?tw=3000&th=3600',
    category: 'apparel',
    w: 3000,
    h: 3600,
    ratio: '5:6',
    description: 'Smaller apparel-artwork workspace for toddler shirt prints.',
    aliases: ['3t shirt design', 'toddler shirt print'],
  }),
];

const requestedImageSizeTerms = [
  'amazon listing',
  'a4 paper',
  'a logo',
  'album',
  'amazon product listing',
  'adobe stock',
  'album cover',
  'adult medium shirt',
  'a large shirt',
  'a 3t shirt',
  'blog post',
  'behance portfolio',
  'back of shirt',
  'banner',
  'back of hoodie',
  'bluesky',
  'blog',
  'behance project',
  'behance',
  'banner printing',
  'constant contact',
  'cd cover',
  'camera',
  'cnn',
  'constant contact email',
  'child t shirt',
  'carousel instagram',
  'cv',
  'ctet',
  'canva',
  'dsssb',
  'dp',
  'desktop background',
  'desktop wallpaper',
  'distrokid',
  'discord banner',
  'discord',
  'digital camera',
  'discord emoji',
  'discord pfp',
  'email signature',
  'email',
  'etsy listing',
  'ebay listing',
  'eventbrite',
  'email marketing',
  'email newsletter',
  'etsy',
  'email signature outlook what is the standard image size',
  'facebook ads',
  'facebook post',
  'flipkart listing',
  'fb post',
  'facebook and instagram post',
  'facebook profile picture',
  'facebook',
  'facebook event',
  'facebook cover photo',
  'facebook event cover',
  'google ads',
  'group d',
  'google form header',
  'gds',
  'google business post',
  'gmail signature',
  'google forms',
  'google business profile',
  'google my business post',
  'google discover',
  'hat',
  'html',
  'hero section',
  'hinge',
  'header of website',
  'html background',
  'hd',
  'header',
  'horizontal',
  'hong kong visa',
  'instagram dp',
  'instagram post',
  'instagram',
  'instagram story',
  'instagram reels',
  'instagram profile picture',
  'instagram carousel',
  'iphone',
  'iphone wallpaper',
  'ig',
  'jee main',
  'journal',
  'job',
  'jotform',
  'jee',
  'japan visa',
  'japan visa application',
  'jee application form',
  'job application',
  'kids shirt',
  'koozie',
  'kids small shirt',
  'kids medium shirt',
  'kindle cover',
  'krita',
  'kindle',
  'kahoot',
  'klaviyo',
  'kickstarter',
  'linkedin post',
  'laptop wallpaper',
  'linkedin cover image',
  'landscape',
  'linkedin profile picture',
  'logo',
  'linkedin featured section',
  'linkedin banner',
  'linkedin',
  'linkedin article',
  'meta ads',
  'mobile wallpaper',
  'mobile view',
  'mobile',
  'meesho listing',
  'mobile screen',
  'microsoft forms',
  'medium shirt',
  'mailchimp',
  'microsoft forms header',
  'neet',
  'neet 2026',
  'neet 2025',
  'newsletter',
  'nextdoor post',
  'notion cover',
  'newborn onesie',
  'nextdoor',
  'notion',
  'ntpc',
  'outlook signature',
  'online',
  'open graph',
  'oci card',
  'oci',
  'oman visa',
  'ojas',
  'post on facebook',
  'post on instagram',
  'pan card',
  'printing',
  'ppt slide',
  'phone wallpaper',
  'passport',
  'pan card online',
  'projector screen',
  'passport size photo',
  'police clearance certificate',
  'qatar visa',
  'qatar id picture size for queen bed',
  'qid picture size for qatar visa',
  'best quality sharepoint',
  'quick links best',
  'gwen edible',
  'quarter sheet cake image size quality increase',
  'rrb',
  'rrb group d',
  'reels',
  'rtps',
  'res message',
  'reddit post',
  'redbubble',
  'resume',
  'reddit imade size for resnet50',
  'ssc',
  'social media posts',
  'ssc cglform',
  'sharepoint banner',
  'shirts',
  'shopify products',
  'substack post',
  'shopify',
  'squarespace',
  'substack',
  't shirt design',
  'tv screen',
  'teams background',
  'tiktok',
  't shirt',
  'text message',
  'tiktok post',
  'twitter',
  'toddler shirt',
  'upsc',
  'upsc 2026',
  'upsc form',
  'upwork project catalog',
  'upwork portfolio',
  'us visa',
  'upload',
  'upwork',
  'uae visa',
  'upsssc pet',
  'voter id',
  'viva engage post',
  'video',
  'visa',
  'vinyl on shirts',
  'vinted',
  'viva engage',
  'veadotube',
  'viber',
  'vit',
  'whatsapp dp',
  'website',
  'wallpaper',
  'whatsapp profile',
  'website banner',
  'whatsapp status',
  'whatsapp',
  'wordpress blog post',
  'whatsapp broadcast',
  'website background',
  'youtube shorts',
  'youtube banner',
  'youtube',
  'youtube banner converter',
  'youtube thumbnail',
  'youtube video',
  'yt banner',
  'youtube post',
  'youtube channel background',
  'youtube community post',
  'zoom background',
  'zomato',
  'zoom waiting room',
  'zillow',
  'zoom profile',
  'zoom',
  'zairyu card picture size for zoom background',
];

interface InferredImageSizeSpec {
  category: ImageSizeForCategory;
  w: number;
  h: number;
  ratio: string;
  href?: string;
  description?: string;
}

const exactTermSpecs: Record<string, InferredImageSizeSpec> = {
  'amazon listing': { category: 'marketplace', w: 1000, h: 1000, ratio: '1:1' },
  'amazon product listing': { category: 'marketplace', w: 1000, h: 1000, ratio: '1:1' },
  'adobe stock': { category: 'marketplace', w: 4000, h: 3000, ratio: '4:3' },
  'a4 paper': { category: 'print', w: 2480, h: 3508, ratio: '1:1.414', href: '/print-a4-portrait-size' },
  'a logo': { category: 'website', w: 512, h: 512, ratio: '1:1' },
  'album': { category: 'popular', w: 3000, h: 3000, ratio: '1:1' },
  'album cover': { category: 'popular', w: 3000, h: 3000, ratio: '1:1' },
  'cd cover': { category: 'print', w: 1417, h: 1417, ratio: '1:1' },
  'banner': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'banner printing': { category: 'print', w: 3000, h: 1000, ratio: '3:1' },
  'blog post': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'blog': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'behance portfolio': { category: 'website', w: 1400, h: 1050, ratio: '4:3' },
  'behance project': { category: 'website', w: 1400, h: 1050, ratio: '4:3' },
  'behance': { category: 'website', w: 1400, h: 1050, ratio: '4:3' },
  'bluesky': { category: 'social', w: 1200, h: 675, ratio: '16:9' },
  'desktop background': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'desktop wallpaper': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'discord banner': { category: 'messaging', w: 960, h: 540, ratio: '16:9' },
  'discord': { category: 'messaging', w: 128, h: 128, ratio: '1:1' },
  'discord emoji': { category: 'messaging', w: 128, h: 128, ratio: '1:1' },
  'discord pfp': { category: 'messaging', w: 128, h: 128, ratio: '1:1' },
  'email signature': { category: 'email', w: 300, h: 100, ratio: '3:1' },
  'gmail signature': { category: 'email', w: 300, h: 100, ratio: '3:1' },
  'outlook signature': { category: 'email', w: 300, h: 100, ratio: '3:1' },
  'email signature outlook what is the standard image size': { category: 'email', w: 300, h: 100, ratio: '3:1' },
  'email': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'email marketing': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'email newsletter': { category: 'email', w: 600, h: 600, ratio: '1:1' },
  'newsletter': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'constant contact': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'constant contact email': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'mailchimp': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'klaviyo': { category: 'email', w: 600, h: 200, ratio: '3:1' },
  'etsy listing': { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' },
  'etsy': { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' },
  'ebay listing': { category: 'marketplace', w: 1600, h: 1600, ratio: '1:1' },
  'flipkart listing': { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' },
  'meesho listing': { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' },
  'shopify products': { category: 'marketplace', w: 2048, h: 2048, ratio: '1:1' },
  'shopify': { category: 'marketplace', w: 2048, h: 2048, ratio: '1:1' },
  'squarespace': { category: 'website', w: 2048, h: 1365, ratio: '3:2' },
  'vinted': { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' },
  'redbubble': { category: 'marketplace', w: 4200, h: 4800, ratio: '7:8' },
  'zomato': { category: 'marketplace', w: 1200, h: 800, ratio: '3:2' },
  'zillow': { category: 'marketplace', w: 1536, h: 1152, ratio: '4:3' },
  'google ads': { category: 'display-ads', w: 300, h: 250, ratio: '6:5' },
  'google business post': { category: 'professional', w: 750, h: 750, ratio: '1:1' },
  'google business profile': { category: 'professional', w: 720, h: 720, ratio: '1:1' },
  'google my business post': { category: 'professional', w: 750, h: 750, ratio: '1:1' },
  'google discover': { category: 'website', w: 1200, h: 628, ratio: '1.91:1' },
  'google form header': { category: 'professional', w: 1600, h: 400, ratio: '4:1', href: '/google-forms-header-image-size' },
  'google forms': { category: 'professional', w: 1600, h: 400, ratio: '4:1', href: '/google-forms-header-image-size' },
  'microsoft forms': { category: 'professional', w: 1600, h: 400, ratio: '4:1' },
  'microsoft forms header': { category: 'professional', w: 1600, h: 400, ratio: '4:1' },
  'jotform': { category: 'professional', w: 1600, h: 400, ratio: '4:1' },
  'eventbrite': { category: 'professional', w: 2160, h: 1080, ratio: '2:1' },
  'html': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'html background': { category: 'website', w: 1920, h: 1080, ratio: '16:9' },
  'hero section': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'header of website': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'header': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'website': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'website banner': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'website background': { category: 'website', w: 1920, h: 1080, ratio: '16:9' },
  'open graph': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'wordpress blog post': { category: 'website', w: 1200, h: 628, ratio: '1.91:1' },
  'sharepoint banner': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'best quality sharepoint': { category: 'website', w: 1920, h: 640, ratio: '3:1' },
  'quick links best': { category: 'website', w: 1024, h: 683, ratio: '3:2' },
  'notion cover': { category: 'website', w: 1500, h: 600, ratio: '2.5:1' },
  'notion': { category: 'website', w: 1500, h: 600, ratio: '2.5:1' },
  'substack post': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'substack': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'cnn': { category: 'website', w: 1200, h: 675, ratio: '16:9' },
  'hd': { category: 'video', w: 1280, h: 720, ratio: '16:9' },
  'horizontal': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'landscape': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'video': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'tv screen': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'projector screen': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'teams background': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'zoom background': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'zoom waiting room': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'zoom': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'zoom profile': { category: 'video', w: 500, h: 500, ratio: '1:1' },
  'wallpaper': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'iphone': { category: 'video', w: 1206, h: 2622, ratio: '19.5:9', href: '/screen-iphone-16-pro-size' },
  'iphone wallpaper': { category: 'video', w: 1206, h: 2622, ratio: '19.5:9', href: '/screen-iphone-16-pro-size' },
  'laptop wallpaper': { category: 'video', w: 1920, h: 1080, ratio: '16:9' },
  'mobile wallpaper': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'mobile view': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'mobile': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'mobile screen': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'phone wallpaper': { category: 'video', w: 1080, h: 1920, ratio: '9:16' },
  'camera': { category: 'professional', w: 3000, h: 2000, ratio: '3:2' },
  'digital camera': { category: 'professional', w: 3000, h: 2000, ratio: '3:2' },
  'canva': { category: 'website', w: 1200, h: 630, ratio: '1.91:1' },
  'krita': { category: 'website', w: 1920, h: 1080, ratio: '16:9' },
  'distrokid': { category: 'popular', w: 3000, h: 3000, ratio: '1:1' },
  'kindle cover': { category: 'popular', w: 1600, h: 2560, ratio: '1:1.6' },
  'kindle': { category: 'popular', w: 1600, h: 2560, ratio: '1:1.6' },
  'kickstarter': { category: 'marketplace', w: 1024, h: 576, ratio: '16:9' },
  'kahoot': { category: 'education', w: 1200, h: 675, ratio: '16:9' },
  'ppt slide': { category: 'professional', w: 1920, h: 1080, ratio: '16:9' },
  'upwork project catalog': { category: 'marketplace', w: 1000, h: 750, ratio: '4:3' },
  'upwork portfolio': { category: 'marketplace', w: 1000, h: 750, ratio: '4:3' },
  'upwork': { category: 'marketplace', w: 250, h: 250, ratio: '1:1' },
  'linkedin cover image': { category: 'professional', w: 1584, h: 396, ratio: '4:1', href: '/linkedin-cover-image-size' },
  'linkedin profile picture': { category: 'professional', w: 400, h: 400, ratio: '1:1' },
  'linkedin featured section': { category: 'professional', w: 1200, h: 627, ratio: '1.91:1' },
  'linkedin article': { category: 'professional', w: 1200, h: 644, ratio: '1.86:1' },
  'linkedin': { category: 'professional', w: 1200, h: 628, ratio: '1.91:1', href: '/linkedin-post-image-size' },
  'meta ads': { category: 'social', w: 1080, h: 1080, ratio: '1:1' },
  'social media posts': { category: 'social', w: 1080, h: 1080, ratio: '1:1' },
  'dp': { category: 'social', w: 500, h: 500, ratio: '1:1' },
  'hinge': { category: 'social', w: 1080, h: 1350, ratio: '4:5' },
  'nextdoor': { category: 'social', w: 1200, h: 628, ratio: '1.91:1' },
  'nextdoor post': { category: 'social', w: 1200, h: 628, ratio: '1.91:1' },
  'reddit post': { category: 'social', w: 1200, h: 800, ratio: '3:2' },
  'reddit imade size for resnet50': { category: 'misc', w: 224, h: 224, ratio: '1:1' },
  'viva engage': { category: 'social', w: 1200, h: 675, ratio: '16:9' },
  'viva engage post': { category: 'social', w: 1200, h: 675, ratio: '16:9' },
  'veadotube': { category: 'video', w: 512, h: 512, ratio: '1:1' },
  'viber': { category: 'messaging', w: 400, h: 400, ratio: '1:1' },
  'whatsapp': { category: 'messaging', w: 640, h: 640, ratio: '1:1' },
  'whatsapp dp': { category: 'messaging', w: 640, h: 640, ratio: '1:1', href: '/whatsapp-profile-photo-size' },
  'whatsapp profile': { category: 'messaging', w: 640, h: 640, ratio: '1:1', href: '/whatsapp-profile-photo-size' },
  'whatsapp status': { category: 'messaging', w: 1080, h: 1920, ratio: '9:16', href: '/whatsapp-status-size' },
  'whatsapp broadcast': { category: 'messaging', w: 1080, h: 1080, ratio: '1:1' },
  'text message': { category: 'messaging', w: 1080, h: 1080, ratio: '1:1' },
  'res message': { category: 'messaging', w: 1080, h: 1080, ratio: '1:1' },
  'facebook ads': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/facebook-ad-square-size' },
  'facebook post': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/facebook-post-image-size' },
  'fb post': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/facebook-post-image-size' },
  'facebook and instagram post': { category: 'social', w: 1080, h: 1080, ratio: '1:1' },
  'facebook profile picture': { category: 'social', w: 170, h: 170, ratio: '1:1', href: '/facebook-profile-photo-size' },
  'facebook': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/facebook-post-image-size' },
  'facebook event': { category: 'social', w: 1200, h: 628, ratio: '1.91:1', href: '/facebook-event-cover-size' },
  'facebook cover photo': { category: 'social', w: 820, h: 312, ratio: '2.62:1', href: '/facebook-cover-photo-size' },
  'facebook event cover': { category: 'social', w: 1200, h: 628, ratio: '1.91:1', href: '/facebook-event-cover-size' },
  'instagram': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/instagram-square-post-size' },
  'ig': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/instagram-square-post-size' },
  'instagram dp': { category: 'social', w: 320, h: 320, ratio: '1:1', href: '/instagram-profile-photo-size' },
  'instagram post': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/instagram-square-post-size' },
  'instagram story': { category: 'social', w: 1080, h: 1920, ratio: '9:16', href: '/instagram-story-size' },
  'instagram reels': { category: 'social', w: 1080, h: 1920, ratio: '9:16', href: '/instagram-reel-size' },
  'reels': { category: 'social', w: 1080, h: 1920, ratio: '9:16', href: '/instagram-reel-size' },
  'instagram profile picture': { category: 'social', w: 320, h: 320, ratio: '1:1', href: '/instagram-profile-photo-size' },
  'instagram carousel': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/instagram-carousel-slide-size' },
  'carousel instagram': { category: 'social', w: 1080, h: 1080, ratio: '1:1', href: '/instagram-carousel-slide-size' },
  'tiktok': { category: 'video', w: 1080, h: 1920, ratio: '9:16', href: '/tiktok-video-size' },
  'tiktok post': { category: 'video', w: 1080, h: 1920, ratio: '9:16', href: '/tiktok-video-size' },
  'twitter': { category: 'social', w: 1200, h: 675, ratio: '16:9', href: '/twitter-image-size' },
  'youtube shorts': { category: 'video', w: 1080, h: 1920, ratio: '9:16', href: '/youtube-shorts-size' },
  'youtube banner': { category: 'video', w: 2560, h: 1440, ratio: '16:9', href: '/youtube-channel-banner-size' },
  'youtube': { category: 'video', w: 1280, h: 720, ratio: '16:9', href: '/youtube-thumbnail-size' },
  'youtube banner converter': { category: 'video', w: 2560, h: 1440, ratio: '16:9', href: '/youtube-channel-banner-size' },
  'youtube thumbnail': { category: 'video', w: 1280, h: 720, ratio: '16:9', href: '/youtube-thumbnail-size' },
  'youtube video': { category: 'video', w: 1920, h: 1080, ratio: '16:9', href: '/youtube-video-1080p-size' },
  'yt banner': { category: 'video', w: 2560, h: 1440, ratio: '16:9', href: '/youtube-channel-banner-size' },
  'youtube post': { category: 'video', w: 1080, h: 1080, ratio: '1:1', href: '/youtube-community-post-size' },
  'youtube channel background': { category: 'video', w: 2560, h: 1440, ratio: '16:9', href: '/youtube-channel-banner-size' },
  'youtube community post': { category: 'video', w: 1080, h: 1080, ratio: '1:1', href: '/youtube-community-post-size' },
  // Indian exams — unique dimensions
  'gate': { category: 'education', w: 240, h: 320, ratio: '3:4', description: 'GATE application photo workspace: 240×320 px, white background. Confirm the current GATE notice.' },
  'gate 2025': { category: 'education', w: 240, h: 320, ratio: '3:4', description: 'GATE 2025 photo workspace: 240×320 px.' },
  'gate 2026': { category: 'education', w: 240, h: 320, ratio: '3:4', description: 'GATE 2026 photo workspace: 240×320 px.' },
  'cat': { category: 'education', w: 180, h: 240, ratio: '3:4', description: 'CAT application photo workspace: 180×240 px. Confirm the official CAT bulletin before uploading.' },
  'xat': { category: 'education', w: 180, h: 240, ratio: '3:4', description: 'XAT application photo workspace: 180×240 px.' },
  'snap': { category: 'education', w: 200, h: 230, ratio: '20:23', description: 'SNAP application photo workspace: 200×230 px, JPEG, white background.' },
  'nmat': { category: 'education', w: 200, h: 230, ratio: '20:23', description: 'NMAT application photo workspace: 200×230 px.' },
  'cmat': { category: 'education', w: 200, h: 230, ratio: '20:23', description: 'CMAT application photo workspace: 200×230 px.' },
  // US visa / immigration — 2×2 inch = 600×600 px at 300 DPI
  'us passport photo': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'US passport photo: 2×2 inch (600×600 px at 300 DPI), white background, State Department spec.' },
  'compress photo for us passport': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'Compress US passport photo under 240 KB for online applications. 2×2 inch, white background.' },
  'uscis photo': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'USCIS application photo: 2×2 inch (600×600 px), white background, full-face.' },
  'uscis photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'USCIS photo requirements: 2×2 inch (600×600 px at 300 DPI), white background.' },
  'uscis photo size in kb': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'USCIS photo: 2×2 inch, under 240 KB for online filing.' },
  'green card photo': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'Green card application photo: 2×2 inch (600×600 px). Confirm USCIS requirements.' },
  'green card photo size': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'USCIS green card photo: 2×2 inch (600×600 px), white background.' },
  'naturalization photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'N-400 naturalization photo: 2×2 inch (600×600 px at 300 DPI).' },
  'compress photo for uscis form': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'USCIS form photo: 2×2 inch, compress under 240 KB.' },
  'i-485 photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'I-485 (green card) photo: 2×2 inch, white background, USCIS compliant.' },
  'h1b visa photo size': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'H-1B visa photo workspace: 2×2 inch (600×600 px).' },
  'f1 student visa photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'F-1 student visa photo: 2×2 inch, white background.' },
  'opt application photo size': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'OPT (F-1 extension) photo: 2×2 inch (600×600 px), USCIS white background.' },
  'global entry photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'Global Entry enrollment photo: 2×2 inch (600×600 px).' },
  'tsa precheck photo size': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'TSA PreCheck photo: standard 2×2 inch (600×600 px).' },
  'nexus card photo requirements': { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'NEXUS card photo: 2×2 inch (600×600 px), white or off-white background.' },
  // US professional license / exam photos — 2×2 inch
  'bar exam application photo size': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'Bar exam application photo: typically 2×2 inch (600×600 px). Confirm your state bar.' },
  'real estate license exam photo': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'Real estate license exam photo: 2×2 inch (600×600 px). Check your state licensing board.' },
  'nclex registration photo size': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'NCLEX registration photo: 2×2 inch (600×600 px).' },
  'usmle photo requirements': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'USMLE / NBME registration photo: 2×2 inch (600×600 px), plain white background.' },
  'cpa exam registration photo': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'CPA exam (NASBA) registration photo: 2×2 inch (600×600 px).' },
  'cfa exam photo requirements': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'CFA exam registration photo: 2×2 inch (600×600 px), plain background.' },
  'lsat photo requirements': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'LSAT registration photo: 2×2 inch (600×600 px), LSAC requirements.' },
  'mcat application photo size': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'MCAT (AMCAS) application photo: check AAMC requirements.' },
  'gre registration photo requirements': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'GRE registration photo: ETS-style ID photo, 2×2 inch (600×600 px).' },
  'gmat photo requirements': { category: 'education', w: 180, h: 240, ratio: '3:4', description: 'GMAT profile photo workspace: 180×240 px.' },
  'sat registration photo size': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'SAT registration photo: College Board ID photo requirements.' },
  'common app photo upload size': { category: 'education', w: 600, h: 600, ratio: '1:1', description: 'Common App photo: check your school portal size requirements.' },
  // US document scans — letter-size at 200 DPI
  'compress image for tax documents': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Tax document scan: 1700×2200 px (US Letter at 200 DPI). Compress before uploading to TurboTax, H&R Block, or IRS portal.' },
  'turbotax document upload size': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'TurboTax document upload: letter-size scan, keep under 5 MB.' },
  'h&r block document upload size': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'H&R Block document scan: US Letter, keep under 5 MB.' },
  'mortgage application document upload size': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Mortgage document scan: US Letter at 200 DPI (1700×2200 px), compressed for lender portals.' },
  'bank statement photo size for mortgage': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Bank statement for mortgage: scan at 200 DPI (1700×2200 px), under 5 MB.' },
  'compress pay stub for loan application': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Pay stub for loan: letter-size scan at 200 DPI, compressed for upload.' },
  'insurance claim photo upload size': { category: 'document', w: 1200, h: 900, ratio: '4:3', description: 'Insurance claim photo: landscape 1200×900 px works for most claim portals.' },
  'compress image for court filing': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Court document scan: US Letter at 200 DPI (1700×2200 px). Check your court filing rules.' },
  'court document scan upload size': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Court filing document: letter-size scan, typically under 10 MB per file.' },
  'legal document photo size for upload': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'Legal document upload: US Letter at 200 DPI scan, compressed for court or law firm portals.' },
  'fafsa document upload size': { category: 'document', w: 1700, h: 2200, ratio: '17:22', description: 'FAFSA document upload: letter-size scan under 5 MB.' },
  // US real estate
  'mls listing photo size requirements': { category: 'marketplace', w: 1600, h: 1200, ratio: '4:3', description: 'MLS listing photo: 1600×1200 px (4:3 landscape), JPEG. Many MLSs require landscape.' },
  'compress real estate photo for mls': { category: 'marketplace', w: 1600, h: 1200, ratio: '4:3', description: 'Real estate photo for MLS: 1600×1200 px (4:3), JPEG recommended.' },
  'real estate headshot photo size': { category: 'professional', w: 400, h: 400, ratio: '1:1', description: 'Real estate agent headshot: square 400×400 px minimum for MLS and portal profiles.' },
  'airbnb listing photo requirements': { category: 'marketplace', w: 1024, h: 683, ratio: '3:2', description: 'Airbnb listing photo: 1024×683 px minimum, 3:2 ratio, JPEG.' },
  'vrbo photo upload size': { category: 'marketplace', w: 1024, h: 683, ratio: '3:2', description: 'VRBO listing photo: 1024×683 px minimum, JPEG.' },
};

function normalizeTerm(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function cropHref(w: number, h: number): string {
  return `/crop-and-resize?tw=${w}&th=${h}`;
}

function inferSpecForTerm(term: string): InferredImageSizeSpec {
  const q = normalizeTerm(term);
  if (exactTermSpecs[q]) return exactTermSpecs[q];

  if (/(visa|passport|oci|voter|qid|zairyu|police clearance|uscis|green card|naturalization|global entry|tsa precheck|nexus card)/.test(q)) {
    return { category: 'visa', w: 600, h: 600, ratio: '1:1', description: 'Document photo workspace. Check the current form rules before final upload.' };
  }
  if (/(jee|neet|upsc|ssc|rrb|group d|ctet|dsssb|gds|ntpc|ojas|rtps|upsssc|vit|job|resume|cv|journal|ibps|sbi po|sbi clerk|rbi grade|lic aao|lic ado|lic assistant|nabard|sebi grade|esic|epfo|irdai|rrb alp|rrb je|rrb sse|rpf|dfccil|afcat|agniveer|crpf|bsf|cisf constable|itbp|assam rifles|coast guard|uppsc|bpsc|mppsc|tnpsc|mpsc|rpsc|wbcs|kpsc|gpsc|opsc|appsc|tspsc|kerala psc|hpsc|jpsc|cgpsc|kvs|nvs|uptet|reet|htet|tntet|maha tet|eamcet|kcet|wbjee|mht cet|bitsat|viteee|fmge|ini cet|jipmer|neet pg|aiims pg|judicial service|high court recruit|police constable|police si|sarathi|e-shram|nsp scholarship|pm kisan|udyam|income tax portal|gst registration|digilocker|aadhaar|epfo uan|nursing license|medical license|nclex|usmle|amcas|npidb|cdl license|faa medical|contractor license|finra|series 7|bar exam|real estate license exam|cpa exam|cfa exam|lsat|mcat|gre|sat registration|common app|act registration|gmat)/.test(q)) {
    return { category: 'education', w: 413, h: 531, ratio: '3:4', description: 'Application photo workspace. Confirm the current exam or portal instructions before final upload.' };
  }
  if (/(shirt|hoodie|hat|koozie|onesie|vinyl)/.test(q)) {
    return { category: 'apparel', w: q.includes('toddler') || q.includes('kids') || q.includes('3t') ? 3000 : 4200, h: q.includes('toddler') || q.includes('kids') || q.includes('3t') ? 3600 : 4800, ratio: q.includes('toddler') || q.includes('kids') || q.includes('3t') ? '5:6' : '7:8' };
  }
  if (/(listing|etsy|ebay|shopify|meesho|vinted|zomato|zillow|redbubble|amazon|flipkart)/.test(q)) {
    return { category: 'marketplace', w: 2000, h: 2000, ratio: '1:1' };
  }
  if (/(email|newsletter|signature|mailchimp|klaviyo|constant contact|gmail|outlook)/.test(q)) {
    return { category: 'email', w: q.includes('signature') ? 300 : 600, h: q.includes('signature') ? 100 : 200, ratio: '3:1' };
  }
  if (/(wallpaper|background|desktop|laptop|mobile|screen|zoom|teams|projector|hd|video|camera)/.test(q)) {
    return { category: 'video', w: /(mobile|phone|iphone)/.test(q) ? 1080 : 1920, h: /(mobile|phone|iphone)/.test(q) ? 1920 : 1080, ratio: /(mobile|phone|iphone)/.test(q) ? '9:16' : '16:9' };
  }
  if (/(facebook|instagram|linkedin|twitter|youtube|tiktok|reddit|whatsapp|discord|viber|bluesky|nextdoor|hinge|social|viva engage)/.test(q)) {
    return { category: 'social', w: 1080, h: 1080, ratio: '1:1' };
  }
  if (/(print|a4|banner printing|cake|flyer|passport size photo)/.test(q)) {
    return { category: 'print', w: 2480, h: 3508, ratio: '1:1.414' };
  }
  if (/(html|website|hero|header|blog|open graph|notion|sharepoint|substack|wordpress|cnn|canva|logo)/.test(q)) {
    return { category: 'website', w: 1200, h: 630, ratio: '1.91:1' };
  }

  return {
    category: 'misc',
    w: 1200,
    h: 1200,
    ratio: '1:1',
    description: 'General image size workspace. Adjust dimensions in the crop and resize tool if the destination has stricter rules.',
  };
}

function requestedTermOptions(baseOptions: ImageSizeForOption[]): ImageSizeForOption[] {
  const byTermOrAlias = new Map<string, ImageSizeForOption>();
  for (const item of baseOptions) {
    byTermOrAlias.set(normalizeTerm(item.term), item);
    for (const alias of item.aliases) byTermOrAlias.set(normalizeTerm(alias), item);
  }

  return [...new Set(requestedImageSizeTerms.map(normalizeTerm))]
    .filter(Boolean)
    .map((term) => {
      const matched = byTermOrAlias.get(term);
      const spec = matched || inferSpecForTerm(term);
      const href = matched?.href || spec.href || cropHref(spec.w || 1200, spec.h || 1200);
      const description = matched?.description || spec.description || `${categoryLabelMap[spec.category]} image size workspace for ${term}.`;

      return option({
        term,
        href,
        category: spec.category,
        w: spec.w,
        h: spec.h,
        ratio: spec.ratio,
        description,
        aliases: [
          ...(matched?.aliases || []),
          `image size for ${term}`,
          `image size of ${term}`,
          `${term} image size`,
          `${term} photo size`,
        ],
        featured: matched?.featured,
      });
    });
}

function withSearchPhrasingAliases(item: ImageSizeForOption): ImageSizeForOption {
  const aliases = new Set([
    ...item.aliases,
    `image size for ${item.term}`,
    `image size of ${item.term}`,
    `${item.term} image size`,
    `${item.term} dimensions`,
    `${item.term} photo size`,
    `${item.term} picture size`,
  ]);

  return {
    ...item,
    aliases: [...aliases],
  };
}

function platformOptions(): ImageSizeForOption[] {
  const intentOptions = imageSizeIntentPages.map((page) =>
    option({
      term: page.keyword.replace(/ image size$/, '').replace(/ size$/, ''),
      href: `/${page.slug}`,
      category: 'popular',
      w: page.format.w,
      h: page.format.h,
      ratio: page.format.ratio,
      description: page.description,
      aliases: [page.h1, page.keyword, ...(page.aliases || [])],
      featured: true,
    })
  );

  const formatOptions = getPlatformPageFormats().map((format) =>
    option({
      term: `${format.platform} ${format.name}`.replace(/\//g, ' ').replace(/\s+/g, ' ').trim().toLowerCase(),
      href: `/${format.slug}`,
      category: format.category,
      w: format.w,
      h: format.h,
      ratio: format.ratio,
      description: `${format.platform} ${format.name} preset: ${format.w}x${format.h} px, ${format.ratio}.`,
      aliases: [
        format.keyword,
        `${format.platform} ${format.name} dimensions`,
        `${format.platform} ${format.name} resolution`,
        ...format.aliases.map((alias) => alias.replace(/-/g, ' ')),
      ],
    })
  );

  return [...intentOptions, ...formatOptions];
}

export function getImageSizeForOptions(): ImageSizeForOption[] {
  const seen = new Set<string>();
  const baseOptions = [...curatedOptions, ...platformOptions()];
  const allOptions = [...baseOptions, ...requestedTermOptions(baseOptions)].map(withSearchPhrasingAliases);

  return allOptions.filter((item) => {
    const key = normalizeTerm(item.term);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function getImageSizeForCategoryLabels(): Record<ImageSizeForCategory, string> {
  return categoryLabelMap;
}
